### ISSUE TITLE
Document that Etherpad must be restarted after installing the plugin to avoid "TypeError: $.alignMenu is not a function"

### ISSUE THREAD

**Issue by tuxayo** [seballot/ep_tables2#21] opened 2016-10-30 17:43 UTC
Given an install of Etherpad-lite 1.6.0 (7dd934f)
on Debian 7
with nodeJS v6.9.1

When I install ep_tables2 (without restarting Etherpad-lite)
And I go to a pad
And I click on the table button
Then nothing happens client side (not even in the logs)
And in the server logs, the following error is logger

```
[2016-10-30 18:31:52.656] [WARN] client - TypeError: $.alignMenu is not a function -- { errorId: '4wCekSMxBGyOdcilFEi0',
  msg: 'TypeError: $.alignMenu is not a function',
  url: 'https://example.org:9001/p/example_pad',
  linenumber: 15,
  userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0' }

```

When I restart etherpad-lite
And I go to a pad
And I click on the table button
Then the table shows up
And no error is logged server-side

**Comment by quenenni** [comment] 2016-11-17 14:31
Hello tuxayo,

I'm sorry to say that I'm not anymore in these add-ons developments.
I'll be happy if someone else can clone the project and go on with it.

**Comment by tuxayo** [comment] 2016-11-18 09:55
No problem. Thanks for making it official.
And thanks for all your work!

**Comment by seballot** [comment] 2018-09-27 07:28
Hello @tuxayo , is this issue still opened? I cannot reproduce it

**Comment by seballot** [comment] 2018-09-27 07:33
closing for now, please reopen if needed

**Closed by seballot** 2018-09-27 07:33 UTC
